### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by zQueal** [EmanueleMinotto/crystal#2]
This is what I'm testing;

```php
<?php

$mf = require_once('framework.php');

$mf('pi', M_PI);

$mf('/', function() use ($mf){
    print_r($mf('pi'));
});

$mf('/test', function(){
    echo 'test';
});

$mf($mf('route_not_found'), function(){
    echo '404';
});
```

I've tested this with both PHP `5.6.12` and `7.0.5` and I get the exact same issues.

-----------------------------------

`/` (as expected) = 3.1415926535898

`/test` (unexpected) = "Apache/2.4.10 (Debian)" error 404 page

All pages other than `/` seem to return a 404, but not even the custom 404, just the regular Apache page.

I've read through the Wiki, but there doesn't seem to be anything there.

**Comment by EmanueleMinotto** [comment]
Hi @zQueal,
if you are using Apache, make sure `mod_rewrite` is enabled and use the following `.htaccess` file:

```
<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>
```

After this you should be able to see `/test` too.
Let me know if this works for you

**Comment by zQueal** [comment]
Hey, great! This works just fine. Think you could fit this into the Wiki?

Great router, by the way!

**Comment by EmanueleMinotto** [comment]
Written in https://github.com/EmanueleMinotto/crystal/wiki/Webserver-Configuration
Thanks for your suggestion :)

**Comment by zQueal** [comment]
Looks great! Tested and working just fine.

Thanks for the kickass router.
